env:
  browser: true
  es6: true
extends:
  'eslint:recommended'
  'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'babel-eslint',
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  quotes: [2, 'single', 'avoid-escape']
