extends: 'stylelint-config-standard'
syntax: scss
plugins:
  - stylelint-scss
  - stylelint-prettier
rules:
  prettier/prettier: [true, { 'singleQuote': true }]
  indentation: 2
  string-quotes: 'single'
  no-duplicate-selectors: true
  color-hex-case: 'lower'
  color-hex-length: 'short'
  color-named: 'never'
  selector-combinator-space-after: 'always'
  selector-attribute-quotes: 'always'
  declaration-block-trailing-semicolon: 'always'
  declaration-colon-space-before: 'never'
  declaration-colon-space-after: 'always'
  property-no-vendor-prefix: true
  value-no-vendor-prefix: true
  number-leading-zero: 'always'
  function-url-quotes: 'always'
  comment-whitespace-inside: 'always'
  comment-empty-line-before: 'always'
  at-rule-no-vendor-prefix: true
  block-opening-brace-space-before: 'always'
  block-closing-brace-newline-after: ['always', ignoreAtRules: ['if', 'else']]
  at-rule-empty-line-before:
    [
      'always',
      ignore:
        [
          'after-comment',
          'first-nested',
          'inside-block',
          'blockless-after-same-name-blockless',
        ],
      ignoreAtRules: ['if', 'else'],
    ]
  at-rule-name-space-after: 'always'
  selector-pseudo-element-colon-notation: 'double'
  selector-pseudo-class-parentheses-space-inside: 'always'
  selector-no-vendor-prefix: true
  media-feature-range-operator-space-before: 'always'
  media-feature-range-operator-space-after: 'always'
  media-feature-parentheses-space-inside: 'always'
  media-feature-name-no-vendor-prefix: true
  media-feature-colon-space-before: 'never'
  media-feature-colon-space-after: 'always'
  at-rule-no-unknown: null
  no-empty-source: null
